### ISSUE TITLE
possibly dead branches

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/scala-partest#102]
The partest repo at the moment has the following branches

 * 1.0.x
 * 1.1.x
 * 2.12.0
 * bump-1.1.2
 * runCommand-public
 * topic/sbt-partest-read

It's not documented what these are for, and I suspect several of them could be deleted.

**Comment by dwijnand** [comment]
I deleted bump-1.1.2, runCommand-public and topic/sbt-partest-read as they were PR branches that weren't deleted.

2.12.0 is associated with #68, for which I've left a message.

the other two I assume are long-term branches.

calling this "done" - Seth revert if you disagree
