### ISSUE TITLE
update branches and readmes now that re-in-sourcing is complete for 2.13

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-partest#109]

**Comment by SethTisue** [comment]
readme change: https://github.com/scala/scala-partest/commit/7e0f7060600ab9211b78c03c7e899ccbbccadbd9

and I changed this repo's default branch back to 1.1.x since that's the only semi-living version, in case some change for 2.12.x becomes necessary

considered archiving the repo on the theory that further changes are unlikely, but meh.

**Comment by dwijnand** [comment]
IMO this can soft-archived (in the repo description and readme), and hard-archived once scala/scala 2.12.x is no longer supported/maintained.

**Comment by SethTisue** [comment]
repo description and readme are updated

**Comment by SethTisue** [comment]
all issues closed

**Comment by SethTisue** [comment]
wiki disabled (it was empty)
