### ISSUE TITLE
Integration test: run scala test suite for PR validation

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-partest#11]
In sbt:
```
set version := "1.0.0-local"
publishM2
```

Then, over in the scala/scala checkout,
edit `versions.properties` so that `partest.version.number=1.0.0-local`.
`rm build/pack/partest.properties` to have the build recreate the partest classpath, and run the test suite using `test/partest`.

**Comment by SethTisue** [comment]
this is done, isn't it?
