### ISSUE TITLE
Consolidate Scala.js fork

### ISSUE THREAD

**Issue by gkossakowski** [scala/scala-partest#30]
Quoting @sjrd from gkossakowski/scala#2 explaining reasons for forking partest:

> At least, we had to replace
> https://github.com/scala/scala-partest-interface/blob/master/src/main/scala/tools/partest/TestingInterface.scala#L75
> by
> https://github.com/scala-js/scala-js/blob/master/partest/src/main/scala/scala/tools/partest/scalajs/PartestInterface.scala#L97
> and
> https://github.com/scala/scala-partest-interface/blob/master/src/main/scala/tools/partest/TestingInterface.scala#L90
> by
> https://github.com/scala-js/scala-js/blob/master/partest/src/main/scala/scala/tools/partest/scalajs/PartestInterface.scala#L113
> 
> I don't remember if there were other things we needed to change.

The task would be to make those things configurable so Scala.js could tweak whatever it needs to tweak instead of forking the whole project.

**Comment by odersky** [comment]
Good timing!

In fact, Vera will work on a reconfigurable partest to also work with
dotty. The first change here will be that partest can no longer assume
there's a Global class to override. Maybe we can work together so that this
fits the bill for everyone?

Cheers

 - Martin





On Thu, Feb 12, 2015 at 4:46 PM, Grzegorz Kossakowski <
notifications@github.com> wrote:

> Quoting @sjrd <https://github.com/sjrd> from gkossakowski/scala#2
> <https://github.com/gkossakowski/scala/pull/2> explaining reasons for
> forking partest:
>
> At least, we had to replace
>
> https://github.com/scala/scala-partest-interface/blob/master/src/main/scala/tools/partest/TestingInterface.scala#L75
> by
>
> https://github.com/scala-js/scala-js/blob/master/partest/src/main/scala/scala/tools/partest/scalajs/PartestInterface.scala#L97
> and
>
> https://github.com/scala/scala-partest-interface/blob/master/src/main/scala/tools/partest/TestingInterface.scala#L90
> by
>
> https://github.com/scala-js/scala-js/blob/master/partest/src/main/scala/scala/tools/partest/scalajs/PartestInterface.scala#L113
>
> I don't remember if there were other things we needed to change.
>
> The task would be to make those things configurable so Scala.js could
> tweak whatever it needs to tweak instead of forking the whole project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scala/scala-partest/issues/30>.
>



-- 
Martin Odersky
EPFL

**Comment by gkossakowski** [comment]
Nice collision! Could you point her at this ticket and ask to drop a comment here? It would be great to hear from her and see if she could kill three birds with one stone.

**Comment by SethTisue** [comment]
presumptively closing, let me know if this is somehow still active or relevant
