### ISSUE TITLE
Partest shouldn't pick up just any old `java` command

### ISSUE THREAD

**Issue by som-snytt** [scala/scala-partest#48]
Partest shouldn't pick up just any old `java` command from the environment.

I've always had `alias partest8="JAVACMD='${SCALA_JAVACMD}' JAVA_HOME='${SCALA_JAVA_HOME}' ./test/partest"` which seems a bit much.

**Comment by som-snytt** [comment]
Duplicates https://issues.scala-lang.org/browse/SI-7786

**Comment by SethTisue** [comment]
consider running partest through sbt instead. that's how the CI scripts will soon be doing it.

**Comment by som-snytt** [comment]
I was reminded by https://gitter.im/lampepfl/dotty?at=56b47ec16002fae41579f9bf but I haven't tried it.

**Comment by lrytz** [comment]
https://github.com/scala/scala-partest/pull/62
