### ISSUE TITLE
Mistyped test name shouldn't test the world

### ISSUE THREAD

**Issue by som-snytt** [scala/scala-partest#60]
That thing where it filters out non-tests and if there's nothing left, runs all tests? Really annoying when I happen to mistype. Some paths do look especially like tests, so if one of those is not an existing file, then please don't test the world.

**Comment by SethTisue** [comment]
maybe now that @dwijnand fixed `partest --grep` he'd like to tackle this one too \</nerdsnipe>

**Comment by dwijnand** [comment]
I've not broken my Ctrl-C buttons yet.. but soon(tm)..

**Comment by SethTisue** [comment]
at least partest running inside sbt is actually Ctrl-C-able these days...!

**Comment by dwijnand** [comment]
Indeed. I need to reverse-engineer how that's the case because I miss it in every other sbt build.

**Comment by dwijnand** [comment]
oh man! @martijnhoekstra 🍾!
