### ISSUE TITLE
Partest detects wrong java exectuable on Windows

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/scala-partest#70]
Partest tries to use `java.dll` as the java command by default

I expect to provide a PR to fix that this evening

**Comment by som-snytt** [comment]
Now I remember why that code looks familiar.

What JDK is this? I see `jdkhome/jre/bin/java.dll` on latest Oracle. Partest looks in `jdkhome/bin`.

**Comment by som-snytt** [comment]
Actually, `util.Properties.jdkHome` will use `$JAVA_HOME` or `java.home`. So that's helpful.

**Comment by martijnhoekstra** [comment]
closed by https://github.com/scala/scala-partest/pull/71
