### ISSUE TITLE
Flags parsing doesn't do "foo bar"

### ISSUE THREAD

**Issue by som-snytt** [scala/scala-partest#79]
The .flags file should allow
```
-Dscala.repl.prompt="%nevil scala> "
```
because otherwise it's just evil.

Why are we so terrified of parsing quoted strings? It's the third rail of parsing.

**Comment by som-snytt** [comment]
I don't remember what I was doing last spring, but https://github.com/scala/scala-partest/pull/91

Note that `SessionTest` only supports the standard prompt anyway.

The PR leverages an existing convention that a multiline option file is taken as one element per line without further parsing. The line is not trimmed, but blank lines are dropped.

**Comment by SethTisue** [comment]
closing old scala-partest issues that seem unlikely to get noticed here now that we've re-in-sourced

**Comment by som-snytt** [comment]
This would be closed as fixed, in the unlikely event that anyone ever needs this feature in the history of the world, or the scala world.

**Comment by hrhino** [comment]
That's the other meaning of "unlikely to get noticed", then.

**Comment by dwijnand** [comment]
_scribbles on hand with finger... resolution: fixed_

**Comment by som-snytt** [comment]
_draws wistfully in the sand with a piece of driftwood... fixed_
