### ISSUE TITLE
--dryrun

### ISSUE THREAD

**Issue by som-snytt** [scala/scala-partest#93]
Sometimes I don't have time for the `run` tests to complete locally, but it would be nice to at least compile them before asking Jenkins to give it a run. I propose `--dryrun` to mean compile-only the executable tests, `run` and `jvm`.

**Comment by dwijnand** [comment]
I think if you want to mean "compile-only" you might want to consider naming the flag `--compile-only` instead.

**Comment by som-snytt** [comment]
I was going for the pun on `--run`, but as a modifier, I could go for `--no-exec --pos --run`. It can't be `--compile-only` because `--neg` fails to compile by definition. :)

**Comment by hrhino** [comment]
I've been thinking of making this for a while now. `partest run` might be short for `partest --run-nothing-else` on my poor laptop. So big 👍 on this.

**Comment by som-snytt** [comment]
Last night I tried working on a PR on my dottir's MacBook Jr while watching Black Lightning, but I wound up plugging in. There were three episodes to catch up on. Luckily, I was awake for the blue-blood supermoon as it set in the west. It looks just like the photo in the newspaper from 2015, except the dottir woke up to go out and see it.

**Comment by dwijnand** [comment]
`--no-exec` (or `--no-run`) sounds good on this side of the peanut gallery

**Comment by SethTisue** [comment]
closing old scala-partest issues that seem unlikely to get noticed here now that we've re-in-sourced
