### ISSUE TITLE
Current dir is on classpath during `run` test

### ISSUE THREAD

**Issue by som-snytt** [scala/scala-partest#94]
It looks like cwd is on the classpath when partest runs. A REPL test fails because it tries to run method `test` imported from a previous line (under tweaked name binding). Presumably `test` package is introduced by `./test/files`.

```
scala> for (i <- 1 to 8) test(i)
<console>:16: error: reference to test is ambiguous;
it is both defined in package <root> and imported subsequently by
import test
       for (i <- 1 to 8) test(i)
                         ^
```

**Comment by SethTisue** [comment]
gah

**Comment by som-snytt** [comment]
Well, maybe something else is going on. I'll check it out soon.

Edit: since I'm not going to make it to fifth grade band concert, I changed the method to `ftest` and it ran as expected.

**Comment by SethTisue** [comment]
closing old scala-partest issues that seem unlikely to get noticed here now that we've re-in-sourced
